//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_18
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_order
    {
        public int id { get; set; }
        public string Email_User { get; set; }
        public int item_number { get; set; }
        public string product_name { get; set; }
    
        public virtual buyers buyers { get; set; }
    }
}
